<?php
declare(strict_types=1);

namespace App\Controllers;

use App\Core\{Auth, Audit, Controller, Csrf, DB, Flash, View};
use App\Models\{Asset, AssetReturn, Assignment, Catalog, Dashboard, Employee, Maintenance};
use Throwable;

final class AssetController extends Controller {
    private Asset $model;private Catalog $cat;
    public function __construct(){Auth::requireLogin();$this->model=new Asset();$this->cat=new Catalog();}
    public function index():void{$f=['q'=>trim($_GET['q']??''),'type_id'=>$_GET['type_id']??'','status_id'=>$_GET['status_id']??'','area_id'=>$_GET['area_id']??''];$p=max(1,(int)($_GET['page']??1));$this->view('assets',['mode'=>'index','title'=>'Inventario','result'=>$this->model->list($f,$p,(int)config('app.items_per_page',15)),'filters'=>$f]+$this->catalogs());}
    public function create():void{$this->view('assets',['mode'=>'form','title'=>'Nuevo activo','item'=>null]+$this->catalogs());}
    public function store():void{Csrf::verify();$d=$this->payload();$er=$this->validate($d,['asset_type_id'=>'required','status_id'=>'required','serial_number'=>'max:150']);if($er)$this->errors($er,$_POST,'assets/create');try{$id=$this->model->save($d,$this->specs(),Auth::id());Audit::log('Inventario','CREAR','asset',$id,null,$d);Flash::success('Activo registrado correctamente.');redirect('assets/'.$id);}catch(Throwable $e){Flash::error('No se pudo registrar: '.$e->getMessage());$_SESSION['_old']=$_POST;redirect('assets/create');}}
    public function show(string $id):void{$a=$this->model->find((int)$id);if(!$a)abort(404,'Activo no encontrado.');$this->view('assets',['mode'=>'show','title'=>$a['asset_code'],'item'=>$a]);}
    public function edit(string $id):void{$a=$this->model->find((int)$id);if(!$a)abort(404);$this->view('assets',['mode'=>'form','title'=>'Editar '.$a['asset_code'],'item'=>$a]+$this->catalogs());}
    public function update(string $id):void{Csrf::verify();$old=$this->model->find((int)$id);if(!$old)abort(404);$d=$this->payload();$er=$this->validate($d,['asset_type_id'=>'required','status_id'=>'required']);if($er)$this->errors($er,$_POST,'assets/'.$id.'/edit');try{$this->model->save($d,$this->specs(),Auth::id(),(int)$id);Audit::log('Inventario','ACTUALIZAR','asset',(int)$id,$old,$d);Flash::success('Activo actualizado.');redirect('assets/'.$id);}catch(Throwable $e){Flash::error($e->getMessage());redirect('assets/'.$id.'/edit');}}
    public function importForm():void{$this->view('assets',['mode'=>'import','title'=>'Importar inventario']);}
    public function importCsv():void{Csrf::verify();if(empty($_FILES['csv']['tmp_name'])){Flash::error('Selecciona un CSV.');redirect('assets/import');}$h=fopen($_FILES['csv']['tmp_name'],'r');$headers=fgetcsv($h,0,',');if(!$headers){Flash::error('CSV vacío.');redirect('assets/import');}$headers=array_map(fn($x)=>trim(strtolower($x)),$headers);$ok=0;$errors=[];while(($row=fgetcsv($h,0,','))!==false){if(count($row)!==count($headers))continue;$r=array_combine($headers,$row);try{$type=$this->findByName('asset_types',$r['tipo']??'');if(!$type)throw new \RuntimeException('Tipo inexistente: '.($r['tipo']??''));$status=$this->findByCode('asset_statuses','DISPONIBLE');$brand=$this->findOrCreate('brands',$r['marca']??'');$model=$this->findModel($brand,$r['modelo']??'');$area=$this->findOrCreate('areas',$r['area']??'');$location=$this->findLocation($area,$r['ubicacion']??'');$supplier=$this->findOrCreate('suppliers',$r['proveedor']??'');$d=['legacy_code'=>$r['codigo_anterior']??'','asset_type_id'=>$type,'brand_id'=>$brand,'model_id'=>$model,'status_id'=>$status,'current_area_id'=>$area,'location_id'=>$location,'serial_number'=>$r['serie']??'','hostname'=>$r['hostname']??'','ip_address'=>$r['ip']??'','mac_address'=>$r['mac']??'','imei1'=>$r['imei1']??'','imei2'=>$r['imei2']??'','phone_number'=>$r['telefono']??'','purchase_date'=>$r['fecha_compra']??'','invoice_number'=>$r['factura']??'','supplier_id'=>$supplier,'cost'=>$r['costo']??'','warranty_end'=>$r['fin_garantia']??'','notes'=>$r['observaciones']??''];$this->model->save($d,[],Auth::id());$ok++;}catch(Throwable $e){$errors[]=$e->getMessage();}}fclose($h);Flash::success("Se importaron $ok activos.");if($errors)Flash::warning(implode(' | ',array_slice($errors,0,4)));redirect('assets');}
    private function catalogs():array{return ['types'=>$this->cat->all('asset_types'),'statuses'=>$this->cat->all('asset_statuses'),'brands'=>$this->cat->all('brands'),'models'=>$this->cat->all('models'),'areas'=>$this->cat->all('areas'),'locations'=>$this->cat->all('locations'),'suppliers'=>$this->cat->all('suppliers')];}
    private function payload():array{return ['legacy_code'=>trim($_POST['legacy_code']??''),'asset_type_id'=>(int)($_POST['asset_type_id']??0),'brand_id'=>(int)($_POST['brand_id']??0),'model_id'=>(int)($_POST['model_id']??0),'status_id'=>(int)($_POST['status_id']??0),'current_area_id'=>(int)($_POST['current_area_id']??0),'location_id'=>(int)($_POST['location_id']??0),'serial_number'=>trim($_POST['serial_number']??''),'hostname'=>trim($_POST['hostname']??''),'ip_address'=>trim($_POST['ip_address']??''),'mac_address'=>trim($_POST['mac_address']??''),'imei1'=>trim($_POST['imei1']??''),'imei2'=>trim($_POST['imei2']??''),'phone_number'=>trim($_POST['phone_number']??''),'purchase_date'=>trim($_POST['purchase_date']??''),'invoice_number'=>trim($_POST['invoice_number']??''),'supplier_id'=>(int)($_POST['supplier_id']??0),'cost'=>trim($_POST['cost']??''),'warranty_end'=>trim($_POST['warranty_end']??''),'notes'=>trim($_POST['notes']??'')];}
    private function specs():array{$keys=$_POST['spec_key']??[];$vals=$_POST['spec_value']??[];$o=[];foreach($keys as $i=>$k)if(trim($k)!=='')$o[trim($k)]=trim($vals[$i]??'');return $o;}
    private function findByName(string $t,string $n):?int{if(trim($n)==='')return null;$s=DB::pdo()->prepare("SELECT id FROM $t WHERE LOWER(name)=LOWER(?) LIMIT 1");$s->execute([trim($n)]);$v=$s->fetchColumn();return $v?(int)$v:null;}
    private function findByCode(string $t,string $c):int{$s=DB::pdo()->prepare("SELECT id FROM $t WHERE code=?");$s->execute([$c]);return (int)$s->fetchColumn();}
    private function findOrCreate(string $t,string $n):?int{if(trim($n)==='')return null;$id=$this->findByName($t,$n);if($id)return $id;$s=DB::pdo()->prepare("INSERT INTO $t(name,active) VALUES(?,1)");$s->execute([trim($n)]);return (int)DB::pdo()->lastInsertId();}
    private function findModel(?int $brand,string $n):?int{if(trim($n)==='')return null;$s=DB::pdo()->prepare('SELECT id FROM models WHERE brand_id<=>? AND LOWER(name)=LOWER(?)');$s->execute([$brand,trim($n)]);$v=$s->fetchColumn();if($v)return(int)$v;$s=DB::pdo()->prepare('INSERT INTO models(brand_id,name,active) VALUES(?,?,1)');$s->execute([$brand,trim($n)]);return(int)DB::pdo()->lastInsertId();}
    private function findLocation(?int $area,string $n):?int{if(trim($n)==='')return null;$s=DB::pdo()->prepare('SELECT id FROM locations WHERE area_id<=>? AND LOWER(name)=LOWER(?)');$s->execute([$area,trim($n)]);$v=$s->fetchColumn();if($v)return(int)$v;$s=DB::pdo()->prepare('INSERT INTO locations(area_id,name,active) VALUES(?,?,1)');$s->execute([$area,trim($n)]);return(int)DB::pdo()->lastInsertId();}
}
