<?php
declare(strict_types=1);

namespace App\Models;

use App\Core\DB;
use PDO;
use Throwable;

final class Activo extends ModeloBase {
    public function list(array $f,int $page,int $per):array{
        $w=['a.active=1'];$p=[];if($f['q']??''){$w[]='(a.asset_code LIKE :q OR a.legacy_code LIKE :q OR a.serial_number LIKE :q OR a.hostname LIKE :q OR a.imei1 LIKE :q OR a.phone_number LIKE :q)';$p['q']='%'.$f['q'].'%';}
        foreach(['type_id'=>'a.asset_type_id','status_id'=>'a.status_id','area_id'=>'a.current_area_id'] as $k=>$c)if(!empty($f[$k])){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}
        $where=implode(' AND ',$w);$s=$this->db->prepare("SELECT COUNT(*) FROM activos a WHERE $where");$s->execute($p);$total=(int)$s->fetchColumn();$off=($page-1)*$per;
        $sql="SELECT a.*,t.name type_name,s.name status_name,s.color,b.name brand_name,m.name model_name,ar.name area_name,l.name location_name,CONCAT(e.first_name,' ',e.last_name) employee_name FROM activos a JOIN tipos_activo t ON t.id=a.asset_type_id JOIN estados_activo s ON s.id=a.status_id LEFT JOIN marcas b ON b.id=a.brand_id LEFT JOIN modelos m ON m.id=a.model_id LEFT JOIN areas ar ON ar.id=a.current_area_id LEFT JOIN ubicaciones l ON l.id=a.location_id LEFT JOIN trabajadores e ON e.id=a.current_employee_id WHERE $where ORDER BY a.id DESC LIMIT $per OFFSET $off";$s=$this->db->prepare($sql);$s->execute($p);return ['rows'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>(int)ceil($total/$per)];
    }
    public function find(int $id):?array{$s=$this->db->prepare("SELECT a.*,t.name type_name,s.name status_name,s.color,b.name brand_name,m.name model_name,ar.name area_name,l.name location_name,CONCAT(e.first_name,' ',e.last_name) employee_name,sup.name supplier_name FROM activos a JOIN tipos_activo t ON t.id=a.asset_type_id JOIN estados_activo s ON s.id=a.status_id LEFT JOIN marcas b ON b.id=a.brand_id LEFT JOIN modelos m ON m.id=a.model_id LEFT JOIN areas ar ON ar.id=a.current_area_id LEFT JOIN ubicaciones l ON l.id=a.location_id LEFT JOIN trabajadores e ON e.id=a.current_employee_id LEFT JOIN proveedores sup ON sup.id=a.supplier_id WHERE a.id=?");$s->execute([$id]);$a=$s->fetch();if(!$a)return null;$s=$this->db->prepare('SELECT spec_key,spec_value FROM especificaciones_activo WHERE asset_id=? ORDER BY spec_key');$s->execute([$id]);$a['specs']=$s->fetchAll();$s=$this->db->prepare('SELECT am.*,u.name user_name FROM movimientos_activo am LEFT JOIN usuarios u ON u.id=am.user_id WHERE am.asset_id=? ORDER BY am.id DESC LIMIT 50');$s->execute([$id]);$a['movements']=$s->fetchAll();$s=$this->db->prepare('SELECT * FROM mantenimientos WHERE asset_id=? ORDER BY id DESC');$s->execute([$id]);$a['mantenimientos']=$s->fetchAll();return $a;}
    public function available():array{return $this->db->query("SELECT a.id,a.asset_code,a.serial_number,t.name type_name,b.name brand_name,m.name model_name FROM activos a JOIN tipos_activo t ON t.id=a.asset_type_id JOIN estados_activo s ON s.id=a.status_id LEFT JOIN marcas b ON b.id=a.brand_id LEFT JOIN modelos m ON m.id=a.model_id WHERE a.active=1 AND s.code='DISPONIBLE' ORDER BY t.name,a.asset_code")->fetchAll();}
    public function save(array $d,array $specs,int $user,?int $id=null):int{
        $this->db->beginTransaction();try{
            if($id){$sql='UPDATE activos SET legacy_code=?,asset_type_id=?,brand_id=?,model_id=?,status_id=?,current_area_id=?,location_id=?,serial_number=?,hostname=?,ip_address=?,mac_address=?,imei1=?,imei2=?,phone_number=?,purchase_date=?,invoice_number=?,supplier_id=?,cost=?,warranty_end=?,notes=?,updated_by=?,updated_at=NOW() WHERE id=?';$args=$this->args($d);$args[]=$user;$args[]=$id;$this->db->prepare($sql)->execute($args);$this->db->prepare('DELETE FROM especificaciones_activo WHERE asset_id=?')->execute([$id]);}
            else{$s=$this->db->prepare('CALL sp_generar_codigo_activo(?,@code)');$s->execute([$d['asset_type_id']]);$s->closeCursor();$code=$this->db->query('SELECT @code')->fetchColumn();$sql='INSERT INTO activos(asset_code,legacy_code,asset_type_id,brand_id,model_id,status_id,current_area_id,location_id,serial_number,hostname,ip_address,mac_address,imei1,imei2,phone_number,purchase_date,invoice_number,supplier_id,cost,warranty_end,notes,active,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)';$args=array_merge([$code],$this->args($d),[$user,$user]);$this->db->prepare($sql)->execute($args);$id=(int)$this->db->lastInsertId();$this->db->prepare("INSERT INTO movimientos_activo(asset_id,movement_type,to_status_id,to_area_id,notes,user_id) VALUES(?,'REGISTRO',?,?,?,?)")->execute([$id,$d['status_id'],$d['current_area_id']?:null,'Registro inicial',$user]);}
            $s=$this->db->prepare('INSERT INTO especificaciones_activo(asset_id,spec_key,spec_value) VALUES(?,?,?)');foreach($specs as $k=>$v)if(trim($k)!==''&&trim($v)!=='')$s->execute([$id,trim($k),trim($v)]);$this->db->commit();return $id;
        }catch(Throwable $e){$this->db->rollBack();throw $e;}
    }
    private function args(array $d):array{return [$d['legacy_code']?:null,$d['asset_type_id'],$d['brand_id']?:null,$d['model_id']?:null,$d['status_id'],$d['current_area_id']?:null,$d['location_id']?:null,$d['serial_number']?:null,$d['hostname']?:null,$d['ip_address']?:null,$d['mac_address']?:null,$d['imei1']?:null,$d['imei2']?:null,$d['phone_number']?:null,$d['purchase_date']?:null,$d['invoice_number']?:null,$d['supplier_id']?:null,$d['cost']?:null,$d['warranty_end']?:null,$d['notes']?:null];}
    public function export():array{return $this->db->query('SELECT * FROM vw_inventario_general ORDER BY asset_code')->fetchAll();}
}
