<?php
namespace App\Models;

use App\Core\DB;
use PDO;
use Throwable;

abstract class Model {protected PDO $db;public function __construct(){$this->db=DB::pdo();}}

final class Catalog extends Model {
    public array $allowed=['areas'=>'Áreas','locations'=>'Ubicaciones','asset_types'=>'Tipos de activo','asset_statuses'=>'Estados','brands'=>'Marcas','models'=>'Modelos','suppliers'=>'Proveedores'];
    public function all(string $table):array{if(!isset($this->allowed[$table]))throw new \InvalidArgumentException('Catálogo inválido');return $this->db->query("SELECT * FROM $table WHERE active=1 ORDER BY name")->fetchAll();}
    public function create(string $table,array $d):int{
        if(!isset($this->allowed[$table]))throw new \InvalidArgumentException('Catálogo inválido');
        if($table==='asset_types'){$s=$this->db->prepare('INSERT INTO asset_types(name,prefix,active) VALUES(?,?,1)');$s->execute([$d['name'],strtoupper($d['prefix'])]);}
        elseif($table==='asset_statuses'){$code=strtoupper(trim((string)($d['code']??'')));if($code===''){$base=iconv('UTF-8','ASCII//TRANSLIT',(string)$d['name'])?:$d['name'];$code=preg_replace('/[^A-Z0-9]+/','_',strtoupper($base));}$s=$this->db->prepare('INSERT INTO asset_statuses(code,name,color,active) VALUES(?,?,?,1)');$s->execute([trim($code,'_'),$d['name'],$d['color']??'secondary']);}
        elseif($table==='models'){$s=$this->db->prepare('INSERT INTO models(brand_id,name,active) VALUES(?,?,1)');$s->execute([$d['brand_id']?:null,$d['name']]);}
        elseif($table==='locations'){$s=$this->db->prepare('INSERT INTO locations(area_id,name,active) VALUES(?,?,1)');$s->execute([$d['area_id']?:null,$d['name']]);}
        else{$s=$this->db->prepare("INSERT INTO $table(name,active) VALUES(?,1)");$s->execute([$d['name']]);}
        return (int)$this->db->lastInsertId();
    }
}

final class Employee extends Model {
    public function all(string $q=''):array{$sql='SELECT e.*,a.name area_name FROM employees e LEFT JOIN areas a ON a.id=e.area_id WHERE e.active=1';$p=[];if($q!==''){$sql.=' AND (e.employee_code LIKE ? OR CONCAT(e.first_name," ",e.last_name) LIKE ? OR e.position LIKE ?)';$x="%$q%";$p=[$x,$x,$x];}$sql.=' ORDER BY e.last_name,e.first_name';$s=$this->db->prepare($sql);$s->execute($p);return $s->fetchAll();}
    public function find(int $id):?array{$s=$this->db->prepare('SELECT * FROM employees WHERE id=?');$s->execute([$id]);return $s->fetch()?:null;}
    public function save(array $d,?int $id=null):int{if($id){$s=$this->db->prepare('UPDATE employees SET employee_code=?,first_name=?,last_name=?,email=?,phone=?,position=?,area_id=?,updated_at=NOW() WHERE id=?');$s->execute([$d['employee_code'],$d['first_name'],$d['last_name'],$d['email']?:null,$d['phone']?:null,$d['position']?:null,$d['area_id']?:null,$id]);return $id;}$s=$this->db->prepare('INSERT INTO employees(employee_code,first_name,last_name,email,phone,position,area_id,active) VALUES(?,?,?,?,?,?,?,1)');$s->execute([$d['employee_code'],$d['first_name'],$d['last_name'],$d['email']?:null,$d['phone']?:null,$d['position']?:null,$d['area_id']?:null]);return (int)$this->db->lastInsertId();}
}

final class Asset extends Model {
    public function list(array $f,int $page,int $per):array{
        $w=['a.active=1'];$p=[];if($f['q']??''){$w[]='(a.asset_code LIKE :q OR a.legacy_code LIKE :q OR a.serial_number LIKE :q OR a.hostname LIKE :q OR a.imei1 LIKE :q OR a.phone_number LIKE :q)';$p['q']='%'.$f['q'].'%';}
        foreach(['type_id'=>'a.asset_type_id','status_id'=>'a.status_id','area_id'=>'a.current_area_id'] as $k=>$c)if(!empty($f[$k])){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}
        $where=implode(' AND ',$w);$s=$this->db->prepare("SELECT COUNT(*) FROM assets a WHERE $where");$s->execute($p);$total=(int)$s->fetchColumn();$off=($page-1)*$per;
        $sql="SELECT a.*,t.name type_name,s.name status_name,s.color,b.name brand_name,m.name model_name,ar.name area_name,l.name location_name,CONCAT(e.first_name,' ',e.last_name) employee_name FROM assets a JOIN asset_types t ON t.id=a.asset_type_id JOIN asset_statuses s ON s.id=a.status_id LEFT JOIN brands b ON b.id=a.brand_id LEFT JOIN models m ON m.id=a.model_id LEFT JOIN areas ar ON ar.id=a.current_area_id LEFT JOIN locations l ON l.id=a.location_id LEFT JOIN employees e ON e.id=a.current_employee_id WHERE $where ORDER BY a.id DESC LIMIT $per OFFSET $off";$s=$this->db->prepare($sql);$s->execute($p);return ['rows'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>(int)ceil($total/$per)];
    }
    public function find(int $id):?array{$s=$this->db->prepare("SELECT a.*,t.name type_name,s.name status_name,s.color,b.name brand_name,m.name model_name,ar.name area_name,l.name location_name,CONCAT(e.first_name,' ',e.last_name) employee_name,sup.name supplier_name FROM assets a JOIN asset_types t ON t.id=a.asset_type_id JOIN asset_statuses s ON s.id=a.status_id LEFT JOIN brands b ON b.id=a.brand_id LEFT JOIN models m ON m.id=a.model_id LEFT JOIN areas ar ON ar.id=a.current_area_id LEFT JOIN locations l ON l.id=a.location_id LEFT JOIN employees e ON e.id=a.current_employee_id LEFT JOIN suppliers sup ON sup.id=a.supplier_id WHERE a.id=?");$s->execute([$id]);$a=$s->fetch();if(!$a)return null;$s=$this->db->prepare('SELECT spec_key,spec_value FROM asset_specifications WHERE asset_id=? ORDER BY spec_key');$s->execute([$id]);$a['specs']=$s->fetchAll();$s=$this->db->prepare('SELECT am.*,u.name user_name FROM asset_movements am LEFT JOIN users u ON u.id=am.user_id WHERE am.asset_id=? ORDER BY am.id DESC LIMIT 50');$s->execute([$id]);$a['movements']=$s->fetchAll();$s=$this->db->prepare('SELECT * FROM maintenances WHERE asset_id=? ORDER BY id DESC');$s->execute([$id]);$a['maintenances']=$s->fetchAll();return $a;}
    public function available():array{return $this->db->query("SELECT a.id,a.asset_code,a.serial_number,t.name type_name,b.name brand_name,m.name model_name FROM assets a JOIN asset_types t ON t.id=a.asset_type_id JOIN asset_statuses s ON s.id=a.status_id LEFT JOIN brands b ON b.id=a.brand_id LEFT JOIN models m ON m.id=a.model_id WHERE a.active=1 AND s.code='DISPONIBLE' ORDER BY t.name,a.asset_code")->fetchAll();}
    public function save(array $d,array $specs,int $user,?int $id=null):int{
        $this->db->beginTransaction();try{
            if($id){$sql='UPDATE assets SET legacy_code=?,asset_type_id=?,brand_id=?,model_id=?,status_id=?,current_area_id=?,location_id=?,serial_number=?,hostname=?,ip_address=?,mac_address=?,imei1=?,imei2=?,phone_number=?,purchase_date=?,invoice_number=?,supplier_id=?,cost=?,warranty_end=?,notes=?,updated_by=?,updated_at=NOW() WHERE id=?';$args=$this->args($d);$args[]=$user;$args[]=$id;$this->db->prepare($sql)->execute($args);$this->db->prepare('DELETE FROM asset_specifications WHERE asset_id=?')->execute([$id]);}
            else{$s=$this->db->prepare('CALL sp_generate_asset_code(?,@code)');$s->execute([$d['asset_type_id']]);$s->closeCursor();$code=$this->db->query('SELECT @code')->fetchColumn();$sql='INSERT INTO assets(asset_code,legacy_code,asset_type_id,brand_id,model_id,status_id,current_area_id,location_id,serial_number,hostname,ip_address,mac_address,imei1,imei2,phone_number,purchase_date,invoice_number,supplier_id,cost,warranty_end,notes,active,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)';$args=array_merge([$code],$this->args($d),[$user,$user]);$this->db->prepare($sql)->execute($args);$id=(int)$this->db->lastInsertId();$this->db->prepare("INSERT INTO asset_movements(asset_id,movement_type,to_status_id,to_area_id,notes,user_id) VALUES(?,'REGISTRO',?,?,?,?)")->execute([$id,$d['status_id'],$d['current_area_id']?:null,'Registro inicial',$user]);}
            $s=$this->db->prepare('INSERT INTO asset_specifications(asset_id,spec_key,spec_value) VALUES(?,?,?)');foreach($specs as $k=>$v)if(trim($k)!==''&&trim($v)!=='')$s->execute([$id,trim($k),trim($v)]);$this->db->commit();return $id;
        }catch(Throwable $e){$this->db->rollBack();throw $e;}
    }
    private function args(array $d):array{return [$d['legacy_code']?:null,$d['asset_type_id'],$d['brand_id']?:null,$d['model_id']?:null,$d['status_id'],$d['current_area_id']?:null,$d['location_id']?:null,$d['serial_number']?:null,$d['hostname']?:null,$d['ip_address']?:null,$d['mac_address']?:null,$d['imei1']?:null,$d['imei2']?:null,$d['phone_number']?:null,$d['purchase_date']?:null,$d['invoice_number']?:null,$d['supplier_id']?:null,$d['cost']?:null,$d['warranty_end']?:null,$d['notes']?:null];}
    public function export():array{return $this->db->query('SELECT * FROM vw_inventory_general ORDER BY asset_code')->fetchAll();}
}

final class Assignment extends Model {
    public function all():array{return $this->db->query("SELECT a.*,CONCAT(e.first_name,' ',e.last_name) employee_name,ar.name area_name,COUNT(ai.id) item_count FROM assignments a JOIN employees e ON e.id=a.employee_id LEFT JOIN areas ar ON ar.id=a.area_id LEFT JOIN assignment_items ai ON ai.assignment_id=a.id GROUP BY a.id ORDER BY a.id DESC")->fetchAll();}
    public function active():array{return $this->db->query("SELECT a.id,a.assignment_number,CONCAT(e.first_name,' ',e.last_name) employee_name,SUM(ai.returned_at IS NULL) pending FROM assignments a JOIN employees e ON e.id=a.employee_id JOIN assignment_items ai ON ai.assignment_id=a.id WHERE a.status IN('CONFIRMADA','PARCIAL') GROUP BY a.id HAVING pending>0 ORDER BY a.id DESC")->fetchAll();}
    public function find(int $id):?array{$s=$this->db->prepare("SELECT a.*,CONCAT(e.first_name,' ',e.last_name) employee_name,e.employee_code,e.position,ar.name area_name,u.name created_by_name FROM assignments a JOIN employees e ON e.id=a.employee_id LEFT JOIN areas ar ON ar.id=a.area_id LEFT JOIN users u ON u.id=a.created_by WHERE a.id=?");$s->execute([$id]);$a=$s->fetch();if(!$a)return null;$s=$this->db->prepare("SELECT ai.*,x.asset_code,x.serial_number,t.name type_name,b.name brand_name,m.name model_name FROM assignment_items ai JOIN assets x ON x.id=ai.asset_id JOIN asset_types t ON t.id=x.asset_type_id LEFT JOIN brands b ON b.id=x.brand_id LEFT JOIN models m ON m.id=x.model_id WHERE ai.assignment_id=? ORDER BY ai.id");$s->execute([$id]);$a['items']=$s->fetchAll();return $a;}
    public function create(int $employee,?int $area,string $notes,array $items,int $user):int{$this->db->beginTransaction();try{$s=$this->db->prepare('CALL sp_assignment_create(?,?,?,?,@id,@number)');$s->execute([$employee,$area,$notes,$user]);$s->closeCursor();$id=(int)$this->db->query('SELECT @id')->fetchColumn();foreach($items as $i){$s=$this->db->prepare('CALL sp_assignment_add_asset(?,?,?,?)');$s->execute([$id,$i['asset_id'],$i['condition'],$user]);$s->closeCursor();}$s=$this->db->prepare('CALL sp_assignment_confirm(?,?)');$s->execute([$id,$user]);$s->closeCursor();$this->db->commit();return $id;}catch(Throwable $e){$this->db->rollBack();throw $e;}}
}

final class AssetReturn extends Model {
    public function all():array{return $this->db->query("SELECT r.*,a.assignment_number,CONCAT(e.first_name,' ',e.last_name) employee_name,COUNT(ri.id) item_count FROM asset_returns r JOIN assignments a ON a.id=r.assignment_id JOIN employees e ON e.id=a.employee_id LEFT JOIN return_items ri ON ri.return_id=r.id GROUP BY r.id ORDER BY r.id DESC")->fetchAll();}
    public function find(int $id):?array{$s=$this->db->prepare("SELECT r.*,a.assignment_number,CONCAT(e.first_name,' ',e.last_name) employee_name,e.employee_code,e.position,ar.name area_name,u.name created_by_name FROM asset_returns r JOIN assignments a ON a.id=r.assignment_id JOIN employees e ON e.id=a.employee_id LEFT JOIN areas ar ON ar.id=a.area_id LEFT JOIN users u ON u.id=r.created_by WHERE r.id=?");$s->execute([$id]);$r=$s->fetch();if(!$r)return null;$s=$this->db->prepare("SELECT ri.*,x.asset_code,x.serial_number,t.name type_name,b.name brand_name,m.name model_name,st.name next_status_name FROM return_items ri JOIN assignment_items ai ON ai.id=ri.assignment_item_id JOIN assets x ON x.id=ai.asset_id JOIN asset_types t ON t.id=x.asset_type_id LEFT JOIN brands b ON b.id=x.brand_id LEFT JOIN models m ON m.id=x.model_id JOIN asset_statuses st ON st.id=ri.next_status_id WHERE ri.return_id=?");$s->execute([$id]);$r['items']=$s->fetchAll();return $r;}
    public function create(int $assignment,string $notes,array $items,int $user):int{$this->db->beginTransaction();try{$s=$this->db->prepare('CALL sp_return_create(?,?,?,@id,@number)');$s->execute([$assignment,$notes,$user]);$s->closeCursor();$id=(int)$this->db->query('SELECT @id')->fetchColumn();foreach($items as $i){$s=$this->db->prepare('CALL sp_return_asset(?,?,?,?,?,?)');$s->execute([$id,$i['item_id'],$i['condition'],$i['damage']?:null,$i['status_id'],$user]);$s->closeCursor();}$s=$this->db->prepare('CALL sp_return_confirm(?,?)');$s->execute([$id,$user]);$s->closeCursor();$this->db->commit();return $id;}catch(Throwable $e){$this->db->rollBack();throw $e;}}
}

final class Maintenance extends Model {
    public function all():array{return $this->db->query("SELECT m.*,a.asset_code,t.name type_name,b.name brand_name,mo.name model_name FROM maintenances m JOIN assets a ON a.id=m.asset_id JOIN asset_types t ON t.id=a.asset_type_id LEFT JOIN brands b ON b.id=a.brand_id LEFT JOIN models mo ON mo.id=a.model_id ORDER BY m.id DESC")->fetchAll();}
    public function open(array $d,int $user):int{$s=$this->db->prepare('CALL sp_maintenance_open(?,?,?,?,?,?,?,@id)');$s->execute([$d['asset_id'],$d['type'],$d['issue']?:null,$d['diagnosis']?:null,$d['actions']?:null,$d['cost']?:0,$user]);$s->closeCursor();return (int)$this->db->query('SELECT @id')->fetchColumn();}
    public function close(int $id,array $d,int $user):void{$s=$this->db->prepare('CALL sp_maintenance_close(?,?,?,?,?,?,?)');$s->execute([$id,$d['diagnosis']?:null,$d['actions']?:null,$d['parts']?:null,$d['cost']?:0,$d['next_date']?:null,$user]);$s->closeCursor();}
}

final class Dashboard extends Model {
    public function data():array{return ['summary'=>$this->db->query('SELECT * FROM vw_dashboard_summary')->fetch(),'byStatus'=>$this->db->query('SELECT * FROM vw_assets_by_status')->fetchAll(),'byType'=>$this->db->query('SELECT * FROM vw_assets_by_type')->fetchAll(),'byArea'=>$this->db->query('SELECT * FROM vw_assets_by_area LIMIT 10')->fetchAll(),'recent'=>$this->db->query("SELECT am.*,a.asset_code,u.name user_name FROM asset_movements am JOIN assets a ON a.id=am.asset_id LEFT JOIN users u ON u.id=am.user_id ORDER BY am.id DESC LIMIT 8")->fetchAll()];}
}
